# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DMahr_SRgJk8kPm7lVtNaidCi44IPUQM
"""

# Commented out IPython magic to ensure Python compatibility.
# Name - Dhairysheel Deshmukh(VIIT)
# The below project is the data analysis of two countries India and U.S.A based on their population and number of beds available in each countries
# Here we have also done the comparitive analysis between the two countries.

# Importing all the libraries required in our project

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

# Reading the csv files of both the countries

df1 = pd.read_csv("hospital_beds_per_india_v1.csv")
df2 = pd.read_csv("hospital_beds_USA_v1.csv")
print("India's Data Before Cleaning")
print(df1)
print("U.S.A's Data Before Cleaning")
print(df2)

# Data cleaning in the following datasets of INDIA and USA by removing the unwanted columns

df_india = df1.drop(['country','county','type','measure','source','source_url'], axis = 1)
print("India's Data After Cleaning")
print(df_india)
df_usa = df2.drop(['country','measure','source_url'], axis = 1)
print("U.S.A's Data After Cleaning")
print(df_usa)

# To find the general statistics using percentages 
# It includes count, mean, standard deviation, min and max value, and the percentages in terms of 25%,50%,75%

print("Describe Function For India Table")
print(df_india.describe())
print("Describe Function For U.S.A Table")
print(df_usa.describe())

# Mean is defined as the average value in the following data

# Median is defined as the middle value in the following data

print("Mean Of Beds In India",df_india.beds.mean())
print("Median Of Beds In India",df_india.beds.median())
print("Mean Of Beds In U.S.A",df_usa.beds.mean())
print("Median Of Beds In U.S.A",df_usa.beds.median())

# The below function gives the correlations between each column and row

print(df_india.corr())
print(df_usa.corr())

# Removing last row 

df_india = df_india.drop(df_india.index[36])

# State vs Population Bar graph for USA

# Since the number of states are quite large in number so we used below fuction which increases the height and width of graph so that more number of entities can be ploted.
plt.rcParams["figure.figsize"] = (20,8)

plt.title('State vs Population Bar graph for USA')
plt.xlabel('Names Of States Of U.S.A')
plt.ylabel('Population Of U.S.A')
plt.bar(df_usa['state'],df_usa['population'],color='gold',edgecolor='purple', hatch='*')

# Conclusion: From this graph we conclude that the states like 'CA','IL','TX' are more densely populated. 
# While the states like 'VT','MT','WY' are not so populated.

# Box Plot for analysis of beds in U.S.A

plt.boxplot([df_usa.beds])
plt.title('Box Plot of beds in U.S.A')

# Conclusion : This plot gives the information regarding the mean number of beds, maximum number of beds and in which range it is saturated.
# As we can see that maximum states has number of beds ranging from 0 to 20 per 1000 people.

# State vs Beds bar graph for USA

plt.rcParams["figure.figsize"] = (20,8)
plt.title('State vs Beds bar graph for USA')
plt.xlabel('Names Of States Of U.S.A')
plt.ylabel('Number Of Beds In U.S.A')
plt.bar(df_usa['state'],df_usa['beds'],color='gold',edgecolor='purple', hatch='*')

# Conclusion : From the graph we can conclude that in the states like 'KS','IA','TX' sufficient amount of beds are present.
# While in the states like 'DC','VT' the number of beds are not adequate.

#Pie chart for type of cases for U.S.A .

typ = ['ICU','ACUTE','OTHER','PSYCHIATRIC']
tot = [df_usa.loc[df_usa['type']=='ICU']['beds'].sum(),df_usa.loc[df_usa['type']=='ACUTE']['beds'].sum(),df_usa.loc[df_usa['type']=='OTHER']['beds'].sum(),df_usa.loc[df_usa['type']=='PSYCHIATRIC']['beds'].sum()]
plt.pie(tot,labels=typ,autopct='%1.1f%%',shadow=True,explode=(0.04,0.04,0.04,0.04),colors=['skyblue','violet','gold','silver'])

# Conclusion: Majority of cases were of type 'ACUTE' contributing about 60.7% . It means majority of patients came for small medical problems.
# It is followed by 'ICU' type . Around 30.7% faced intensive health problems.
# 5.7% were of type 'PSYCHIATRY' i.e they faced problems related to mental disorder.
# And rest 2.8% were of type 'OTHER'.

# Doughnut chart for the source from where we got the information for U.S.A.

df_usa['source'].unique()
rr = ['khn','arcgis']
df_usa['source'].value_counts()
oc = [2301,3412]
explode =(0.05,0.05)
circle = plt.Circle( (0,0),0.7, color='white')
p = plt.gcf()
p.gca().add_artist(circle)
plt.pie(oc,labels=rr,autopct='%1.1f%%',explode = explode,shadow = True,colors=['red','darkblue'])

# Conclusion: Major part of information that is 59.7% was gathered from source 'arcgis' and the rest 40.3% was gathered from source 'khn'.

# State vs Population bar graph for INDIA.
plt.rcParams['figure.figsize']=(20,8)
plt.title('State vs Population bar graph for INDIA')
plt.xlabel('Names Of States Of India')
plt.ylabel('Population Of India')
plt.bar(df_india.state,df_india.population,color='purple',edgecolor='gold', hatch='*')

# Conclusion: Clearly state 'UP' is far ahead from other states in term of population.
# It is followed by the states like 'BR','MH'.
# While the population of states like 'DD','AN' is  quiet low.

# Box Plot for analysis of beds in India

plt.boxplot([df_india.beds])
plt.title('Box Plot of beds in India')

# Conclusion : This plot gives the information regarding the mean number of beds, maximum number of beds and in which range it is saturated.
# As we can see that maximum states has number of beds ranging from 0 to 1.5 per 1000 people.

# State vs Beds lollipop graph for India

plt.rcParams['figure.figsize']=(20,8)
plt.title('State vs Population bar graph for INDIA')
plt.xlabel('Names Of States Of India')
plt.ylabel('Number Of Beds In India')
plt.stem(df_india['state'],df_india['beds'])

# Conclusion : In the states like 'LD','TN','CH','AN' good number of beds are present.
# But in states like 'BR','UP','OR' the number of beds are quiet low .

# Comparison Between India and U.S.A  on the basis of Number of beds.
# Since in the data for India the number of beds are given for particular years only so we have considered it as the latest data.

plt.rcParams['figure.figsize']=(10,8)
pop = [df_india['beds'].sum(),df_usa.loc[df_usa['year']==2019]['beds'].sum()]
nam = ['INDIA','USA']
plt.title('Comparison Between India and U.S.A  on the basis of Number of beds')
plt.xlabel('Names Of Countries')
plt.ylabel('Number Of Beds ')
plt.bar(nam,pop,color=['gold','purple'],edgecolor=['purple','gold'],hatch = '/')

# Conclusion: There are many reasons why U.S.A is called developed country and one such reason is it's health care facility.
# U.S.A is far ahead of india in number of beds available.
# India needs to quickly work after it's health care sector.

# Comparison Between India and U.S.A  on the basis of Number of population.

plt.rcParams['figure.figsize']=(10,8)
pop = [df_india['population'].sum(),df_usa.loc[df_usa['year']==2019]['population'].sum()]
nam = ['INDIA','USA']
plt.title('Comparison Between India and U.S.A  on the basis of Number of population')
plt.xlabel('Names Of Countries')
plt.ylabel('Population Of Countries')
plt.bar(nam,pop,color=['gold','purple'],edgecolor=['purple','gold'],hatch = '/')

# Conclusion : As we can see that population of india is far greater than U.S.A which is almost four times the population of U.S.A .
# Since the area of India is smaller than U.S.A in matter of area so it's population density is also very high.

# Comparison Between India and U.S.A  on the basis of Ratio of Total population and Total bed.

plt.rcParams['figure.figsize']=(10,8)
pop = [df_india['population'].sum()/df_india['beds'].sum(),df_usa.loc[df_usa['year']==2019]['population'].sum()/df_usa.loc[df_usa['year']==2019]['beds'].sum()]
nam = ['INDIA','USA']
plt.title('Comparison Between India and U.S.A  on the basis of Ratio of Total population and Total bed')
plt.xlabel('Names Of Countries')
plt.ylabel('Ratio of Total population and Total bed')
plt.bar(nam,pop,color=['gold','purple'],edgecolor=['purple','gold'],hatch = '/')

# Conclusion: From this graph we will come to know that for how much of population of country there is 1 bed .
# As we can see India's numbers are far greater than U.S.A so it means that in India behind 1 bed there is large amount of population 
# While in case of U.S.A the number of people behind 1 bed is far lower.

# My final Conclusion :
# From the analysis of the above data we can say tha in the countris like India needs to increase the number of beds in country at drastic rates. Since the number of beds are low and population is high so this is the alarming condition for India.
# While in case of U.S.A sufficient amount of  beds are present.

# My review regarding data provided :
# For many states data for only some years was present.
# Also in many areas data was not clear and was insufficient.